[project]
org-name= "kavindu"
version= "0.1.0"

[build-options]
observability-included=true

[dependencies]

[platform]
target = "java8"
    [[platform.libraries]]
    artifactId = "mysql-connector-java"
    version = "8.0.11"
    path = "/usr/lib/ballerina/distributions/ballerina-slp3/bre/lib/mysql-connector-java-8.0.11.jar"
    groupId = "mysql"
